# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0005_auto_20170410_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
